### ISSUE TITLE
Getting error 500 after latest update to the dev branch.

### ISSUE THREAD

**Issue by Candrom87** [vontainment/v-gpt-qdrant-api#4]
I've been playing around in flowise with custom tools and had it working fine before your latest update to the dev branch.

Now when creating new collection for example, I see this output in the log:

```
Error processing request: `host` param is not expected to contain protocol (http:// or https://). Try to use `url` parameter instead.
INFO:     10.0.7.4:51340 - "POST /collections HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.9/site-packages/starlette/_utils.py", line 87, in collapse_excgroups
  |     yield
  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 193, in __call__
  |     response_sent.set()
  |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    |     return await self.app(scope, receive, send)
    |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    |     raise exc
    |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 193, in __call__
    |     response_sent.set()
    |   File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/usr/local/lib/python3.9/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    |     raise exc
    |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 191, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "/app/dependencies.py", line 72, in limit_concurrency
    |     raise HTTPException(status_code=500, detail="Internal Server Error")
    | fastapi.exceptions.HTTPException: 500: Internal Server Error
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 193, in __call__
    response_sent.set()
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/app/dependencies.py", line 72, in limit_concurrency
    raise HTTPException(status_code=500, detail="Internal Server Error")
fastapi.exceptions.HTTPException: 500: Internal Server Error
Current active tasks: 1
Error processing request: `host` param is not expected to contain protocol (http:// or https://). Try to use `url` parameter instead.
INFO:     10.0.7.4:51350 - "POST /collections HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.9/site-packages/starlette/_utils.py", line 87, in collapse_excgroups
  |     yield
  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 193, in __call__
  |     response_sent.set()
  |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    |     return await self.app(scope, receive, send)
    |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    |     raise exc
    |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 193, in __call__
    |     response_sent.set()
    |   File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/usr/local/lib/python3.9/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    |     raise exc
    |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 191, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "/app/dependencies.py", line 72, in limit_concurrency
    |     raise HTTPException(status_code=500, detail="Internal Server Error")
    | fastapi.exceptions.HTTPException: 500: Internal Server Error
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 193, in __call__
    response_sent.set()
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/app/dependencies.py", line 72, in limit_concurrency
    raise HTTPException(status_code=500, detail="Internal Server Error")
fastapi.exceptions.HTTPException: 500: Internal Server Error
```

For reference, the following is the "custom tool" javascript function that I created to be able to let an agent create a new collection:
```
const fetch = require('node-fetch');
const userId = $vars.userId;
const body = {
        "collection_name": `${userId}`
    };
const options = {
      method: 'POST',
      headers: {
            'Content-Type': 'application/json'
      },
      body: JSON.stringify(body)
};

const url = `http://memories-api:8060/collections`;

try {
	const response = await fetch(url, options);
	const text = await response.text();
	return text;
} catch (error) {
	console.error(error);
	return '';
}
```

**Comment by vontainment** [comment]
host has to start with http:// or https://
but if you use the latest update to the dev branch its just the host name and uses grpc to connect. to make it faster.

**Comment by vontainment** [comment]
example in docker-compose.yml the env variable should be: QDRANT_HOST: http://qdrant:6333
but in the new updated dev branch as of yesterday it would be: QDRANT_HOST: qdrant

**Comment by vontainment** [comment]
memories-api:
    container_name: memories-api
    image: vontainment/v-gpt-qdrant-api:dev # Use your appropriate image
    restart: always
    depends_on:
      - qdrant
    ports:
      - "8060:8060"
    environment:
      QDRANT_HOST: qdrant #uses grpc to connect to port 6334
      QDRANT_API_KEY:
      #MEMORIES_API_KEY: Optional API key to connect to api
      BASE_URL: http://memories-api
      WORKERS: 1 #uvicorn workers 1 should be enough for personal use
      API_CONCURRENCY: 4 #max embeddings produced similtaniusly. This stops eccessive CPU usage. 
      UVICORN_CONCURRENCY: 32 #this controls the mac connections. Anything over the API_concurrancy value is put in query pool. Anything over this number is rejected.
    volumes:
      - embedding-model:/tmp/fastembed_cache

**Comment by Candrom87** [comment]
Thank you! Works fine now 👍

**Comment by vontainment** [comment]
Awesome. I made some more optimizations today fixing up the imports I had some unneeded. Trying to get this as low resource as I can.

**Comment by vontainment** [comment]
By the way if you're using this with Dify. You can use difys qdrant DB with no conflicts to save resources

**Comment by vontainment** [comment]
I will also admit that I'm not completely knowledgeable in asynchronous python. I still find some of it confusing. So I'm working on trying to make sure that I got that working as efficiently as I can. That's my next objective is to optimize it for CPU usage

**Comment by vontainment** [comment]
There's a variable for memory API key. It's optional. If You said that variable would API key then an API key is required to connect to all the endpoints. If you leave it empty you don't need one. I made it optional like that for when it's being run inside something like dify and isn't expose externally

**Comment by vontainment** [comment]
Just set MEMORIES_API_KEY:

The environmental variables in docker compose

**Comment by Candrom87** [comment]
Thanks, I did notice the api key variable, haven't had a chance to test it yet but will look into it!

I really need to make sure to lock this down appropriately since we'll be working with sensitive user data.

**Comment by vontainment** [comment]
Yeah as long as you set that variable all the endpoints will require it. Basically if the variable isn't set then there's no requirement for an API key but if it is set then it's a requirement

**Comment by vontainment** [comment]
I just updated the DEV branch again. I added Prince statement that shows how long it took to fulfill a request. That way you can adjust the concurrency variable to keep your request time short. If you have too many requests come in at one time being processed at once the amount of time to make a vector can get a lot higher. But if you said it right for your hardware it stays very fast under load. And just put everything into a query and then processes in the other time that way it doesn't time out anybody. 

Though I took out the grpc and went back to http for now. CPU overhead with it making all the connections each time you try to add to the database. I'm still trying to figure out how to make a consistent connection with it. So the variable for host went back to http://qdrant:6333. 

Also made a few other optimizations. Made the query better and replaced a few more computationally heavy lines with better ones.

**Comment by Candrom87** [comment]
Thanks for the heads-up!
I’ll check it out as soon as I get the time and report back!

Having a way to see how long requests take is a very welcome addition! 
Speed and fulfilment of requests is very important, having a way to monitor and balance things out is awesome! 🥳

**Comment by vontainment** [comment]
There print statements so they show up in Docker logs. Is a little counterintuitive because the print command is not really great for optimization. But it's only two of them so I mean it's not like I went print crazy LOL.  Once you find out what's good for your Hardware u can remove them from code if wanted.

I'm also starting a second development branch. Instead of fastembed I'm going to use nomics client. It allows you to take advantage of the models adjustable dimensionality. Like right now everything's at 768 dimensions. That's great for documents but probably not for the memory part. That could probably be much smaller like 128. I'm going to experiment with that

**Comment by vontainment** [comment]
Since you have been using this, do you have any functionality suggestions?

I was thinking about changing create_collections to manage_collections. Wit 2 required parameters and one optional. Collection_Name, Action and optional UUID.  Action would be an action "create, list, delete, forget" The first 3 would directly effect the collections, create it, delete it or list all collections. Forget would require the UUID and would delete a memory entry. I figured put them together like this to lower the amount of tools. Cause on some platforms you have limited endpoints you can use.

I also just started a dev2 branch I made the Model name an env variable to play with other models.

**Comment by Candrom87** [comment]
So I have testet the latest DEV branch update. It seems to be a bit slower than before, otherwise than that, everything's fine!

**Comment by vontainment** [comment]
The dev version currently now have a delete memory function. I changed the create collection endpoint to manage memory. Now has an action parameter, it can be create delete or forget so it can create or delete collections and forget memories. It also now has the option to change the built-in .odel through environmental variable. As for a user fact sheet that's kind of the point of the memory is the deal remember these things If you tell it your name and everything about you it will remember that. If you tell it in the system instructions to use the recall memory when it doesn't know the answer to something. And you would ask it what's my name it would look it up and give it to you

**Comment by vontainment** [comment]
Also it can filter results by a keyword, a sentiment or an entity. So you could always ask it to remember certain things of a particular keyword that you can then use to recall that kind of information

**Comment by vontainment** [comment]
Also I've been testing BAAI/bge-small-en-v1.5. It has 368 dimensions in the vector. It's faster and half the ram nomic. And it works really good for memories because you're not doing documents you're doing more like paragraphs.

**Comment by Candrom87** [comment]
I'm with you on the memory part, except that I think it would be good to have the option to pass pre-defined memories into that "fact-sheet". This enhances the user-experiences in my opinion since we can pass their already-known information, well formatted, into the memory. This way when users first use the agent, they do not have to tell it their name etc.. it already knows.
