### ISSUE TITLE
An error occurred: delete() missing 1 required positional argument: 'points_selector'

### ISSUE THREAD

**Issue by Candrom87** [vontainment/v-gpt-qdrant-api#5]
When passing a POST call to forget a certain memory, I get the following error:

```
An error occurred: delete() missing 1 required positional argument: 'points_selector'
INFO:     10.0.7.4:44426 - "POST /manage_memories HTTP/1.1" 500 Internal Server Error
```

The required params have been correctly passed in the body: memory_bank, action and the UUID of the point to delete.

After skimming through the responsible code, I was wondering if this part is correct:

```
elif Params.action == "forget":
            if Params.uuid is None:
                raise HTTPException(
                    status_code=400, detail="UUID must be provided for forget action"
                )

            # Delete specific memory using UUID
            await Qdrant.delete(
                collection_name=Params.memory_bank, point_ids=[Params.uuid]
            )

            return {
                "message": f"Memory with UUID '{Params.uuid}' has been forgotten from Memory Bank '{Params.memory_bank}'."
            }
```

**Comment by vontainment** [comment]
They don't have the best documentation... I will look into it. but yes its definatly that code snippit.

**Comment by Candrom87** [comment]
I fixed it, but I have no Idea how to use github correctly.. forked the repo, changed the docker compose, and correctly build the image.. but not sure how to create a pull request with only the change that fixes the issue.. 

here's the corrected code:

```
# Delete specific memory using UUID
            await Qdrant.delete(
                    collection_name=Params.memory_bank,
                    points_selector=[Params.uuid]
                )

            return {
                "message": f"Memory with UUID '{Params.uuid}' has been forgotten from Memory Bank '{Params.memory_bank}'."
            }
```

**Comment by vontainment** [comment]
I just pushed the fix, then cam here to tell you and saw you already did what i did lol

**Comment by vontainment** [comment]
Yes you did the pull request correctly
